export const defaultUpgrades = {
  upgrade1: {
    cost: 10,
    owned: 0,
    value: 0.1,
    max: 999999,
    key: "upgrade1",
    id: "clik go brr",
    description:
      "While clicking, gain a % of your NPS as bonus income per upgrade",
  },
  upgrade2: {
    cost: 50,
    owned: 0,
    value: 0.1,
    max: 999999,
    key: "upgrade2",
    id: "I have arthritis",
    description: "Gain 0.5 NPS per CPS per upgrade",
  },
  upgrade3: {
    cost: 100,
    owned: 0,
    value: 2,
    max: 999999,
    key: "upgrade3",
    id: "Big Bucks",
    description: "Gain double per click",
  },
  upgrade4: {
    cost: 100,
    owned: 0,
    value: 0.05,
    max: 20,
    key: "upgrade4",
    id: "Summer Vacation",
    description:
      "During offline time, collect a percentage of the amount produced",
  },
  upgrade5: {
    cost: 100000,
    owned: 0,
    value: 2,
    max: 1,
    key: "upgrade5",
    id: "Super Glue",
    description: "Makes Sticky Notes stickier, thus, doubling their value",
  },
  upgrade6: {
    cost: 5000000,
    owned: 0,
    value: undefined,
    max: 1,
    key: "upgrade6",
    id: "Casino",
    description: "Let's go gambling",
  },
  upgrade7: {
    cost: 10000000,
    owned: 0,
    value: 0.2,
    max: 1,
    key: "upgrade7",
    id: "Middle Management",
    description: "Installing one manager for every 5 workers. Productivity mysteriously improves",
  },
};
