export const defaultVisuals = {
  clearNote: {
    id: "clearNote",
    name: "A Clean Note",
    cost: 0,
    image: undefined,
    owned: true,
    selected: true,
    type: "note",
  },
  smile: {
    id: "smile",
    name: "Smiley Face",
    cost: 100,
    image: require("url:../images/visual/note/happy.webp"),
    owned: false,
    selected: false,
    type: "note",
  },
  schroeder: {
    id: "schroeder",
    name: "Schroeder",
    cost: 10,
    image: require("url:../images/visual/note/SchroederShadow.png"),
    owned: false,
    selected: false,
    type: "note",
  },
  saxophone: {
    id: "saxophone",
    name: "Saxophone",
    cost: 10,
    image: require("url:../images/visual/note/saxophone.webp"),
    owned: false,
    selected: false,
    type: "note",
  },
  trombone: {
    id: "trombone",
    name: "Trombone",
    cost: 10,
    image: require("url:../images/visual/note/trombone.png"),
    owned: false,
    selected: false,
    type: "note",
  },
};
