export const defaultVisuals = {
  clearNote: {
    id: "clearNote",
    name: "A Clean Note",
    cost: 0,
    image: undefined,
    owned: true,
    selected: true,
    type: "note",
  },
  smile: {
    id: "smile",
    name: "Smiley Face",
    cost: 100,
    image: require("url:../images/visual/note/happy.webp"),
    owned: false,
    selected: false,
    type: "note",
  },
  schroeder: {
    id: "schroeder",
    name: "Schroeder",
    cost: 10,
    image: require("url:../images/visual/note/SchroederShadow.png"),
    owned: false,
    selected: false,
    type: "note",
  },
  saxophone: {
    id: "saxophone",
    name: "Saxophone",
    cost: 10,
    image: require("url:../images/visual/note/saxophone.webp"),
    owned: false,
    selected: false,
    type: "note",
  },
  trombone: {
    id: "trombone",
    name: "Trombone",
    cost: 10,
    image: require("url:../images/visual/note/trombone.png"),
    owned: false,
    selected: false,
    type: "note",
  },
  yellowNote: {
    id: "yellowNote",
    name: "Yellow Note",
    cost: 10,
    color: "#feff9c",
    owned: true,
    selected: true,
    type: "note-color",
  },
  blueNote: {
    id: "blueNote",
    name: "Blue Note",
    cost: 10,
    color: "#7afcff",
    owned: false,
    selected: false,
    type: "note-color",
  },
  pinkNote: {
    id: "pinkNote",
    name: "Pink Note",
    cost: 10,
    color: "#ff7eb9",
    owned: false,
    selected: false,
    type: "note-color",
  },
  whiteBackground: {
    id: "whiteBackground",
    name: "White Background",
    cost: 10,
    color: "white",
    owned: true,
    selected: true,
    type: "background",
  },
  blackBackground: {
    id: "blackBackground",
    name: "Black Background",
    cost: 10,
    color: "black",
    owned: false,
    selected: false,
    type: "background",
  },
  greenBackground: {
    id: "greenBackground",
    name: "Green Background",
    cost: 10,
    color: "#c9ffcc",
    owned: false,
    selected: false,
    type: "background",
  },
  gradientBackground: {
    id: "gradientBackground",
    name: "Gradient Background",
    cost: 10,
    color:
      "linear-gradient(90deg,rgba(87, 199, 133, 1) 0%, rgba(87, 199, 133, 1) 20%, rgba(42, 123, 155, 1) 20%, rgba(42, 123, 155, 1) 40%, rgba(87, 199, 133, 1) 40%, rgba(87, 199, 133, 1) 60%, rgba(42, 123, 155, 1) 60%, rgba(42, 123, 155, 1) 80%, rgba(87, 199, 133, 1) 80%)",
    owned: false,
    selected: false,
    type: "background",
  },
  ebackground: {
    id: "ebackground",
    name: "ebackground",
    cost: 10,
    image: require("url:../images/visual/note/happy.webp"),
    owned: false,
    selected: false,
    type: "background",
  },
};
