export const defaultWorkers = {
  worker1: {
    cost: 10,
    owned: 0,
    produce: 1,
    id: "worker1",
    name: "Loose Change",
    description: "Collect coins from couch cushions to buy more notes.",
    visible: false,
    listenerAttached: false,
  },
  worker2: {
    cost: 50,
    owned: 0,
    produce: 5,
    id: "worker2",
    name: "Buy Friend", // Changed from "Buy "Friend"" for consistency
    description: "Buy a real friend to buy you notes.",
    visible: false,
    listenerAttached: false,
  },
  worker3: {
    cost: 150,
    owned: 0,
    produce: 10,
    id: "worker3",
    name: "Pen",
    description: "Make \"important\" notes.",
    visible: false,
    listenerAttached: false,
  },
  worker4: {
    cost: 500,
    owned: 0,
    produce: 20,
    id: "worker4",
    name: "Part Time Job",
    description: "I can't wait to start working.",
    visible: false,
    listenerAttached: false,
  },
  worker5: {
    cost: 1500,
    owned: 0,
    produce: 40,
    id: "worker5",
    name: "Robbery",
    description: "I hate working.",
    visible: false,
    listenerAttached: false,
  },
  worker6: {
    cost: 5000,
    owned: 0,
    produce: 60,
    id: "worker6",
    name: "Numismatics",
    description: "Collects coins. Doesn’t spend them. Slight issue.",
    visible: false,
    listenerAttached: false,
  },
  worker7: {
    cost: 15000,
    owned: 0,
    produce: 80,
    id: "worker7",
    name: "Coin Hoarder",
    description: "An obsession with coin collections leads to note production.",
    visible: false,
    listenerAttached: false,
  },
  onlineShopping: {
    cost: 20000,
    owned: 0,
    produce: 100,
    id: "onlineShopping",
    name: "Online Shopping",
    description: "You only get scammed, sometimes.",
    visible: false,
    listenerAttached: false,
  },
  coffeeIntern: {
    cost: 40000,
    owned: 0,
    produce: 150,
    id: "coffeeIntern",
    name: "Coffee Intern",
    description: "Energizes the office and occasionally makes a decent latte.",
    visible: false,
    listenerAttached: false,
  },
  printerGoblin: {
    cost: 70000,
    owned: 0,
    produce: 250,
    id: "printerGoblin",
    name: "Printer Goblin",
    description: "Lurks near the copier and prints sticky notes at lightning speed.",
    visible: false,
    listenerAttached: false,
  },
  basementInterns: {
    cost: 120000,
    owned: 0,
    produce: 350,
    id: "basementInterns",
    name: "Basement Interns",
    description: "Unpaid and overworked, they generate notes in exchange for 'experience'.",
    visible: false,
    listenerAttached: false,
  },
  hundredHumans: {
    cost: 250000,
    owned: 0,
    produce: 500,
    id: "hundredHumans",
    name: "100 Humans",
    description: "The only thing that can beat a silverback gorilla.",
    visible: false,
    listenerAttached: false,
  },
  internetAdBot: {
    cost: 350000,
    owned: 0,
    produce: 700,
    id: "internetAdBot",
    name: "Internet Ad Bot",
    description: "Runs ads for sticky notes you didn’t know you needed.",
    visible: false,
    listenerAttached: false,
  },
  automationScript: {
    cost: 600000,
    owned: 0,
    produce: 1000,
    id: "automationScript",
    name: "Automation Script",
    description: "A single script replaces 10 interns. No coffee needed.",
    visible: false,
    listenerAttached: false,
  },
  noteFactory: {
    cost: 1200000,
    owned: 0,
    produce: 1600,
    id: "noteFactory",
    name: "Note Factory",
    description: "Industrial-grade note vomit. Glorious.",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 1
  paperPusherPro: {
    cost: 2000000,
    owned: 0,
    produce: 2200,
    id: "paperPusherPro",
    name: "Paper Pusher Pro",
    description: "Elevated from intern to professional note stacker.",
    visible: false,
    listenerAttached: false,
  },
  humanResources: {
    cost: 3000000,
    owned: 0,
    produce: 2800,
    id: "humanResources",
    name: "Human Resources",
    description: "Perhaps allowing hats on Friday will cure their depression?",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 2
  corporateDroneSwarm: {
    cost: 4500000,
    owned: 0,
    produce: 4000,
    id: "corporateDroneSwarm",
    name: "Corporate Drone Swarm",
    description: "A legion of highly caffeinated office workers producing notes in unison.",
    visible: false,
    listenerAttached: false,
  },
  ceoOverlord: {
    cost: 6000000,
    owned: 0,
    produce: 5000,
    id: "ceoOverlord",
    name: "CEO Overlord",
    description: "Does nothing, yet everything gets done. Yells 'synergy' a lot.",
    visible: false,
    listenerAttached: false,
  },
  aiNoteGenerator: {
    cost: 12000000,
    owned: 0,
    produce: 7000,
    id: "aiNoteGenerator",
    name: "AI Note Generator",
    description: "Hallucinates helpful notes after reading the internet for 3 minutes.",
    visible: false,
    listenerAttached: false,
  },
  thirdWorldCountry: {
    cost: 22000000,
    owned: 0,
    produce: 8500,
    id: "thirdWorldCountry",
    name: "Third World Country",
    description: "I wouldn't say free, more like, under new management.",
    visible: false,
    listenerAttached: false,
  },
  warCrimes: {
    cost: 35000000,
    owned: 0,
    produce: 10500,
    id: "warCrimes",
    name: "War Crimes",
    description: "Commit terrible acts, like calling sticky notes \"post-it notes\".",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 3
  lunarNoteMiners: {
    cost: 45000000,
    owned: 0,
    produce: 13000,
    id: "lunarNoteMiners",
    name: "Lunar Note Miners",
    description: "Specialized team mining for rare note isotopes on the Moon.",
    visible: false,
    listenerAttached: false,
  },
  quantumTaskScheduler: {
    cost: 60000000,
    owned: 0,
    produce: 16000,
    id: "quantumTaskScheduler",
    name: "Quantum Task Scheduler",
    description: "Performs tasks before you even think of them. Terrifyingly efficient.",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 4
  martianColonyScribes: {
    cost: 90000000,
    owned: 0,
    produce: 21000,
    id: "martianColonyScribes",
    name: "Martian Colony Scribes",
    description: "The first Martian settlers are surprisingly adept at note creation.",
    visible: false,
    listenerAttached: false,
  },
  quantumStickyLab: {
    cost: 120000000,
    owned: 0,
    produce: 27000,
    id: "quantumStickyLab",
    name: "Quantum Sticky Lab",
    description: "Harvests sticky notes from infinite timelines. Some are cursed.",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 5
  asteroidBeltPaperRoute: {
    cost: 250000000,
    owned: 0,
    produce: 38000,
    id: "asteroidBeltPaperRoute",
    name: "Asteroid Belt Paper Route",
    description: "Delivering bulk sticky notes to various asteroid outposts. High risk, high reward.",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 6
  interstellarNoteTraders: {
    cost: 400000000,
    owned: 0,
    produce: 46000,
    id: "interstellarNoteTraders",
    name: "Interstellar Note Traders",
    description: "Galactic merchants specializing in the exotic note markets of distant star systems.",
    visible: false,
    listenerAttached: false,
  },
  multiverseMerger: {
    cost: 600000000,
    owned: 0,
    produce: 55000,
    id: "multiverseMerger",
    name: "Multiverse Merger",
    description: "Absorbs entire companies across realities. Legally questionable.",
    visible: false,
    listenerAttached: false,
  },
  parallelWorldEmpire: {
    cost: 1000000000,
    owned: 0,
    produce: 80000,
    id: "parallelWorldEmpire",
    name: "Parallel World Empire",
    description: "Gathers sticky notes from countless universes.",
    visible: false,
    listenerAttached: false,
  },
  // New Worker 7
  galacticNoteForge: {
    cost: 2500000000, // 2.5 Billion
    owned: 0,
    produce: 150000,
    id: "galacticNoteForge",
    name: "Galactic Note Forge",
    description: "A Dyson sphere powered factory dedicated to forging notes from raw stellar material.",
    visible: false,
    listenerAttached: false,
  },
  stickyNote: {
    cost: 10000000000000, // 10 Trillion
    owned: 0,
    produce: 100000000, // 100 Million
    id: "stickynote",
    name: "The Sticky Note",
    description: "The One and Only",
    visible: false,
    listenerAttached: false,
  },
};