export const defaultWorkers = {
  worker1: {
    cost: 10,
    owned: 0,
    produce: 1,
    id: "worker1",
    name: "Loose Change",
    description: "Collect coins from couch cushions to buy more notes.",
    visible: false,
    listenerAttached: false,
  },
  worker2: {
    cost: 100,
    owned: 0,
    produce: 5,
    id: "worker2",
    name: `Buy "Friend"`,
    description: "Buy a real friend to buy you notes",
    visible: false,
    listenerAttached: false,
  },
  worker3: {
    cost: 500,
    owned: 0,
    produce: 10,
    id: "worker3",
    name: "Pen",
    description: `Make "important" notes.`,
    visible: false,
    listenerAttached: false,
  },
  worker4: {
    cost: 1000,
    owned: 0,
    produce: 20,
    id: "worker4",
    name: "Part Time Job",
    description: "I can't wait to start working",
    visible: false,
    listenerAttached: false,
  },
  worker5: {
    cost: 10000,
    owned: 0,
    produce: 50,
    id: "worker5",
    name: "Robbery",
    description: "I hate working",
    visible: false,
    listenerAttached: false,
  },
  worker6: {
    cost: 20000,
    owned: 0,
    produce: 70,
    id: "worker6",
    name: "Numismatics",
    description: "Collects coins. Doesn’t *spend* them. Slight issue.",
    visible: false,
    listenerAttached: false,
  },
  onlineShopping: {
    cost: 50000,
    owned: 0,
    produce: 100,
    id: "onlineShopping",
    name: "Online Shopping",
    description: "You only get scammed, sometimes.",
    visible: false,
    listenerAttached: false,
  },
  coffeeIntern: {
    cost: 80000,
    owned: 0,
    produce: 120,
    id: "coffeeIntern",
    name: "Coffee Intern",
    description: "Energizes the office and occasionally makes a decent latte.",
    visible: false,
    listenerAttached: false,
  },

  printerGoblin: {
    cost: 100000,
    owned: 0,
    produce: 140,
    id: "printerGoblin",
    name: "Printer Goblin",
    description:
      "Lurks near the copier and prints sticky notes at lightning speed",
    visible: false,
    listenerAttached: false,
  },
  internetAdBot: {
    cost: 150000,
    owned: 0,
    produce: 180,
    id: "internetAdBot",
    name: "Internet Ad Bot",
    description: "Runs ads for sticky notes you didn’t know you needed.",
    visible: false,
    listenerAttached: false,
  },
  automationScript: {
    cost: 300000,
    owned: 0,
    produce: 300,
    id: "automationScript",
    name: "Automation Script",
    description: "A single script replaces 10 interns. No coffee needed.",
    visible: false,
    listenerAttached: false,
  },
  noteFactory: {
    cost: 500000,
    owned: 0,
    produce: 500,
    id: "noteFactory",
    name: "Note Factory",
    description: "Industrial-grade note vomit. Glorious.",
    visible: false,
    listenerAttached: false,
  },
  quantumTaskScheduler: {
    cost: 5000000,
    owned: 0,
    produce: 5000,
    id: "quantumTaskScheduler",
    name: "Quantum Task Scheduler",
    description:
      "Performs tasks before you even think of them. Terrifyingly efficient.",
    visible: false,
    listenerAttached: false,
  },
  basementInterns: {
    cost: 7500000,
    owned: 0,
    produce: 7500,
    id: "basementInterns",
    name: "Basement Interns",
    description:
      "Unpaid and overworked, they generate notes in exchange for 'experience'.",
    visible: false,
    listenerAttached: false,
  },
  aiNoteGenerator: {
    cost: 25000000,
    owned: 0,
    produce: 20000,
    id: "aiNoteGenerator",
    name: "AI Note Generator",
    description:
      "Hallucinates helpful notes after reading the internet for 3 minutes.",
    visible: false,
    listenerAttached: false,
  },
  quantumStickyLab: {
    cost: 100000000,
    owned: 0,
    produce: 80000,
    id: "quantumStickyLab",
    name: "Quantum Sticky Lab",
    description:
      "Harvests sticky notes from infinite timelines. Some are cursed.",
    visible: false,
    listenerAttached: false,
  },
  ceoOverlord: {
    cost: 500000000,
    owned: 0,
    produce: 250000,
    id: "ceoOverlord",
    name: "CEO Overlord",
    description:
      "Does nothing, yet everything gets done. Yells 'synergy' a lot.",
    visible: false,
    listenerAttached: false,
  },
  multiverseMerger: {
    cost: 2000000000,
    owned: 0,
    produce: 1000000,
    id: "multiverseMerger",
    name: "Multiverse Merger",
    description:
      "Absorbs entire companies across realities. Legally questionable.",
    visible: false,
    listenerAttached: false,
  },
};
