export const defaultWorkers = {
  worker1: {
    cost: 10,
    owned: 0,
    produce: 1,
    id: "worker1",
    name: "Loose Change",
    description: "collect loose change to buy more notes",
  },
  worker2: {
    cost: 100,
    owned: 0,
    produce: 5,
    id: "worker2",
    name: `Buy "Friend"`,
    description: "Buy a real friend to buy you notes",
  },
  worker3: {
    cost: 500,
    owned: 0,
    produce: 10,
    id: "worker3",
    name: "Pen",
    description: `make "important" notes`,
  },
  worker4: {
    cost: 1000,
    owned: 0,
    produce: 20,
    id: "worker4",
    name: "Part Time Job",
    description: "I can't wait to start working",
  },
  worker5: {
    cost: 10000,
    owned: 0,
    produce: 30,
    id: "worker5",
    name: "Robbery",
    description: "I hate working",
  },
  worker6: {
    cost: 50000,
    owned: 0,
    produce: 50,
    id: "worker6",
    name: "Numismatics",
    description: "I love collecting coins",
  },
};
